### ISSUE TITLE
Possible error in the tests.

### ISSUE THREAD

**Issue by einarstensson** [learn-co-curriculum/displaying-associations-rails#9]
In the spec/features/post_spec.rb file, I think the line:

@post.category = Category.create!(name: "Cats")

... should be added (on row 6). Otherwise, the code:

<pre>
<%# app/views/posts/show.html.erb %>
<h2><%= @post.title %></h2>
Category: <%= link_to @post.category.name, category_path(@post.category) %>
<p><%= @post.description %></p>
</pre>

... breaks because the post does'nt have a category. The error I get running bundle exec rspec is:

  1) navigate shows the title on the show page in a h1 tag
     Failure/Error: Category: <%= link_to @post.category.name, category_path(@post.category) %>

```
 ActionView::Template::Error:
   undefined method `name' for nil:NilClass
```

Best,
Einar

**Comment by pickledyamsman** [comment]
@aturkewi This issue is still present. Looks like there is a pending pull request that could fix it but I believe it is for mendel and he is done.

Changing lines 5 and 27 in post_spec.rb to:
`category = Category.create(name: "A Category")
@post = category.posts.create(title: "My Post", description: "My post desc")`

also fixes this.

**Comment by aturkewi** [comment]
Thanks for pointing this out @pickledyamsman I'm going to pass this one along to @Lukeghenco 
He's now in charge of the Rails section :)

**Comment by mendelB** [comment]
Thanks so much all! Closing this issue now.

**Comment by einarstensson** [comment]
Thanks! Glad things worked out.

Best,
Einar

On Wed, Nov 16, 2016 at 11:50 PM, Mendel Blesofsky <notifications@github.com
